---
version: "3"
services:
 devopsdb:
   container_name: devopsdb
   image: vamsi562/flm-practice:db-img
   ports:
     - "3306:3306"

 application:
   image: vamsi562/flm-practice:app-img
   container_name: containerapp
   ports:
     - "1234:8080"
   depends_on:
     - "devopsdb"
